//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Cyberduck")]
[assembly: AssemblyDescription("FTP and Cloud Files Browser")]
[assembly: AssemblyCompany("Cyberduck")]
[assembly: AssemblyProduct("Cyberduck")]
[assembly: AssemblyCopyright("© 2010-2011 Yves Langisch. All rights reserved.")]
[assembly: ComVisible(false)]
[assembly: Guid("5fc1c120-24c7-469d-b52b-9bce20db208d")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]


